---
title: "Chapter 3: Linear Methods for Regression"
author: "Bodo Burger"
date: 2018-05
output:
  rmarkdown::github_document:
    toc: true
---

```{r setup, message=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE,
                      cache = TRUE, cache.path = "cache/",
                      fig.path = "figures/")
set.seed(123)
library("mlr")
library("ggplot2")
theme_set(theme_light())
```

# Linear Regression Models


## Figure 3-3 tail probabilities

```{r figure-3-3-tail-probabilities, fig.asp=.5}
z = seq(1.9, 3, .01)
plot(z, 2 * (1 - pt(z, df = 30)), col = "orange", type = "l", lwd = 1, xlab = "Z", ylab = "Tail Probabilities")
lines(z, 2 * (1 - pt(z, df = 100)), col = "deepskyblue")
lines(z, 2 * (1 - pnorm(z)), col = "aquamarine3")
abline(h = c(.01, .05), lty = 2, lwd = .5)
abline(v = qt(c(.975, .995), df = 30), lty = 2, lwd = .5, col = "orange")
abline(v = qt(c(.975, .995), df = 100), lty = 2, lwd = .5, col = "deepskyblue")
abline(v = qnorm(c(.975, .995)), lty = 2, lwd = .5, col = "aquamarine3")
```

## Table 3-1

```{r}
prostate.data = ElemStatLearn::prostate
#prostate.data$svi = factor(prostate.data$svi)
#prostate.data$gleason = factor(prostate.data$gleason, ordered = TRUE)
prostate.cor = round(cor(subset(prostate.data, subset = train, select = 1:8)), digits = 3)
prostate.cor[upper.tri(prostate.cor, diag = "TRUE")] = ""
knitr::kable(prostate.cor[-1, -8])
```

## Table 3-2

```{r}
train.data = subset(prostate.data, subset = train, select = 1:9)
# predictors need to be standardized
lm.fit = lm(lpsa ~ ., data = train.data)
```



# Links
